# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Razor
email: your-email@domain.com
description: # this means to ignore newlines until "baseurl:"
  Ben Razor is a versatile software developer. Most of his professional career has been devoted to developing web and mobile sports games.
  His favourite playthings are Blender, Ableton Live, Python and JS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  ben-razor

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker 
